Extra Utilities 2 - zh_CN translation review
3TUSK/Temp_LocalizationFile pull request #72
Opened 2017-02-12 04:18 UTC by 3TUSK

Feedbacks needed.

2017-02-12 14:41 UTC, TartaricAcid commented on assets/extrautils2/zh_CN.lang
> +extrautils2.text.climograph=气象图
好像有点问题
![exu2](https://i.imgur.com/frSeHyr.png)

2017-02-12 14:42 UTC, TartaricAcid commented on assets/extrautils2/zh_CN.lang
> +extrautils2.text.i.feel.sharp=我感觉到……sharp.
`sharp`怎么翻译，感觉好多意思

2017-02-12 14:44 UTC, TartaricAcid commented on assets/extrautils2/zh_CN.lang
> +extrautils2.text.climograph=气象图
建议翻译成`气象设备`之类的，因为我看到后面有`在地形改造器%s方块范围内放置气象图`

2017-02-12 14:45 UTC, TartaricAcid commented on assets/extrautils2/zh_CN.lang
> +extrautils2.text.climograph=气象图
建议翻译成`气象设备`之类的，因为我看到后面有`在地形改造器%s方块范围内放置气象图`

2017-02-12 14:47 UTC, TartaricAcid commented on assets/extrautils2/zh_CN.lang
> +extrautils2.text.missing.climographs=缺失气象图：
看起来我的猜测是对的，如果是`气象设备`完美符合这个翻译

2017-02-12 14:47 UTC, TartaricAcid commented on assets/extrautils2/zh_CN.lang
> +extrautils2.text.missing.climographs=缺失气象图：
看来我猜的是对的，`气象设备`符合这个翻译

2017-02-12 14:48 UTC, TartaricAcid commented on assets/extrautils2/zh_CN.lang
> +extrautils2.text.place.climographs.within.s.blocks=在地形改造器%s方块范围内放置气象图
这个也是，气象设备

2017-02-12 14:49 UTC, TartaricAcid commented on assets/extrautils2/zh_CN.lang
> +extrautils2.text.requires.actuators.to.be.attached=每个面都需要紧贴上执行器
这块我翻译错了，应该是`每个面都需要紧贴上具现设备`，这个是描述量子采矿机的

2017-02-12 15:42 UTC, 3TUSK commented on assets/extrautils2/zh_CN.lang
> +extrautils2.text.i.feel.sharp=我感觉到……sharp.
关键是找到这句话在哪里出现的。

2017-02-12 19:34 UTC, 3TUSK commented on assets/extrautils2/zh_CN.lang
> +extrautils2.text.i.feel.sharp=我感觉到……sharp.
我感觉到...灵光一现？

2017-02-13 12:20 UTC, TartaricAcid requested changes

2017-02-13 12:20 UTC, TartaricAcid commented on assets/extrautils2/zh_CN.lang
> +extrautils2.text.hope.you.got.x.receipt=希望你能得到x配方。
我的错，应该是`发票`

2017-02-13 12:20 UTC, TartaricAcid commented on assets/extrautils2/zh_CN.lang
> +extrautils2.text.hope.you.got.x.receipt=希望你能得到x配方。
这段话是买了那个黑心村民的假东西后出现的

2017-02-13 12:20 UTC, TartaricAcid commented on assets/extrautils2/zh_CN.lang
> +extrautils2.text.all.players.can.currently.access=所有的玩家当前都可以访问你的物品栏A
多打了个`A`

2017-02-13 12:20 UTC, TartaricAcid commented on assets/extrautils2/zh_CN.lang
> +extrautils2.text.i.feel.sharp=我感觉到……sharp.
目前还没找到，先保持原样子吧

2017-02-13 12:29 UTC, TartaricAcid commented on assets/extrautils2/zh_CN.lang
> +extrautils2.text.i.feel.sharp=我感觉到……sharp.
目前还没找到，先保持原样子吧

2017-02-22 11:44 UTC, Towdium commented
`使用者`这个翻译是不是有点迷....

2017-02-22 13:30 UTC, 3TUSK commented
User? 执行器？玩家模拟器？&(%&@%#&!%

2017-02-22 15:11 UTC, Towdium commented
恩是user，我觉得执行器好点。他这个原文也是够迷的了

2017-02-22 15:15 UTC, 3TUSK commented
原文的话也只能这么写啊...总不可能写什么Simulator of Using之类的吧...

2017-02-24 15:53 UTC, 3TUSK commented
Will be merged as this on next Monday (Feb. 27th)

2017-02-26 23:30 UTC, merged